---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda Stack

Parameters:
  ChatWorkToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ChatWorkToken

  ChatworkRoomId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ChatworkRoomId

  IoTButtonDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: IoTButtonDSN
    Description: The device serial number (DSN) of the AWS IoT Button. This can be
      found on the back of the button. The DSN must match the pattern of 'G030[A-Z][A-Z][0=9][0-9][0-9][0-5][0-9][1-7][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X]'.

  CertificateARN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CertificateARN
    Description: The Amazon Resource Name (ARN) of the existing AWS IoT certificate.

Resources:
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub iotbutton_${IoTButtonDSN}

  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: iot:Publish
          Effect: Allow
          Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/iotbutton/${IoTButtonDSN}

  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Ref CertificateARN

  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Ref CertificateARN
      ThingName: !Ref IoTThing

  IoTMessageNotiferFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iot-message-notifer
      CodeUri: src/handlers/message_notifier
      Handler: index.handler
      Runtime: python3.6
      AutoPublishAlias: development
      Timeout: 60
      MemorySize: 128
      Role: !GetAtt IoTMessageNotiferFunctionRole.Arn
      Environment:
        Variables:
          CHATWORK_TOKEN: !Sub '${ChatWorkToken}'
          CHATWORK_ROOM_ID: !Sub '${ChatworkRoomId}'
          DATABASE_NAME: room_table
      Events:
        OverflowIngesterRule:
          Type: IoTRule
          Properties:
            AwsIotSqlVersion: 2016-03-23
            Sql: !Sub
              - |
                SELECT * FROM 'iotbutton/${IoTButtonDSN}'
              - IoTTopicRuleGetThingShadowRoleArn: !GetAtt IoTTopicRuleGetThingShadowRole.Arn

  IoTMessageNotiferFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: iot-message-notifer-function-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  IoTTopicRuleGetThingShadowRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub iot-topic-rule-get-thing-shadow-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      Policies:
        - PolicyName: !Sub iot-topic-rule-get-thing-shadow-role-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iot:GetThingShadow
                Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:thing/*

  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: room_table
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
