---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda Stack

Parameters:
  SlackWebhookURL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: SlackWebhookURL

Globals:
  Function:
    Runtime: python3.7
    Timeout: 60
    MemorySize: 128
    AutoPublishAlias: development
    Layers:
      - !Ref UtilsLayer

Resources:
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utils
      Description: logger layer
      ContentUri: src/layers/utils
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain

  MessageNotiferFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: message-notifer
      CodeUri: src/handlers/message_notifier
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Sub '${SlackWebhookURL}'
          DATABASE_NAME: !Ref RoomTable

  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: room_table
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
