---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda Stack

Parameters:
  ChatWorkToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ChatWorkToken

  ChatworkRoomId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ChatworkRoomId

  SlackWebhookURL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: SlackWebhookURL

Resources:
  MessageNotiferFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: message-notifer
      CodeUri: src/handlers/message_notifier
      Handler: index.handler
      Runtime: python3.6
      AutoPublishAlias: development
      Timeout: 60
      MemorySize: 128
      Role: !GetAtt MessageNotiferFunctionRole.Arn
      Environment:
        Variables:
          CHATWORK_TOKEN: !Sub '${ChatWorkToken}'
          CHATWORK_ROOM_ID: !Sub '${ChatworkRoomId}'
          SLACK_WEBHOOK_URL: !Sub '${SlackWebhookURL}'
          DATABASE_NAME: room_table

  MessageNotiferFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: message-notifer-function-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: room_table
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
